/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCompany"];
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/api/objectives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listObjectives"];
        put?: never;
        post: operations["createObjective"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objectives/{objective_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objective_id: components["parameters"]["ObjectiveId"];
            };
            cookie?: never;
        };
        get: operations["getObjective"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objectives/{objective_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objective_id: components["parameters"]["ObjectiveId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objectives/{objective_id}/plan/revise": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objective_id: components["parameters"]["ObjectiveId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revisePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objectives/{objective_id}/plan/approve": {
        parameters: {
            query?: never;
            header: {
                /** @description Reusing a key returns the original run and never starts another. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                objective_id: components["parameters"]["ObjectiveId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approvePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["listRunArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Company: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            mission: string;
            working_rules: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CompanyUpdate: {
            name?: string;
            description?: string;
            mission?: string;
            working_rules?: string[];
        };
        AgentDefinition: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            company_id: string;
            slug: string;
            name: string;
            role: string;
            objective: string;
            responsibilities: string[];
            runtime_model_alias: string;
            prompt_version: string;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AgentUpdate: {
            name?: string;
            role?: string;
            objective?: string;
            responsibilities?: string[];
            runtime_model_alias?: string;
            prompt_version?: string;
            enabled?: boolean;
        };
        /** @enum {string} */
        ObjectiveStatus: "draft" | "planning" | "awaiting_approval" | "approved" | "running" | "completed" | "failed";
        Objective: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            company_id: string;
            title: string;
            desired_outcome: string;
            context: string;
            constraints: string[];
            status: components["schemas"]["ObjectiveStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ObjectiveCreate: {
            title: string;
            desired_outcome: string;
            /** @default  */
            context: string;
            /** @default [] */
            constraints: string[];
        };
        /** @enum {string} */
        WorkItemStatus: "proposed" | "approved" | "running" | "review" | "done" | "failed";
        WorkItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            company_id: string;
            /** Format: uuid */
            objective_id: string;
            /** Format: uuid */
            parent_id?: string | null;
            /** Format: uuid */
            assigned_agent_id: string;
            title: string;
            instructions: string;
            deliverable_type: string;
            status: components["schemas"]["WorkItemStatus"];
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Plan: {
            /** Format: uuid */
            objective_id: string;
            work_items: components["schemas"]["WorkItem"][];
        };
        PlanRevision: {
            feedback: string;
        };
        /** @enum {string} */
        RunStatus: "pending" | "awaiting_approval" | "running" | "completed" | "failed";
        AgentRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            company_id: string;
            /** Format: uuid */
            objective_id: string;
            status: components["schemas"]["RunStatus"];
            graph_version: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            error_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        EventType: "run.created" | "plan.proposed" | "plan.revision_requested" | "plan.approved" | "work.started" | "work.progress" | "artifact.created" | "work.completed" | "work.failed" | "brief.created" | "run.completed" | "run.failed";
        RunEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            company_id: string;
            /** Format: uuid */
            run_id: string;
            sequence: number;
            event_type: components["schemas"]["EventType"];
            summary: string;
            /** @description Size is checked after compact UTF-8 JSON encoding. */
            payload_json: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        Artifact: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            company_id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            work_item_id?: string | null;
            artifact_type: string;
            title: string;
            content_markdown: string;
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: {
        /** @description The company-scoped resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested transition is not allowed in the current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request validation failed. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        AgentId: string;
        ObjectiveId: string;
        RunId: string;
        /** @description Reusing a key returns the original run and never starts another. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The seeded company. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdate"];
            };
        };
        responses: {
            /** @description Updated company. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The company's fixed agent profiles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDefinition"][];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDefinition"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Updated agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDefinition"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listObjectives: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Objectives newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Objective"][];
                };
            };
        };
    };
    createObjective: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectiveCreate"];
            };
        };
        responses: {
            /** @description Created objective. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Objective"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getObjective: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objective_id: components["parameters"]["ObjectiveId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Objective details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Objective"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objective_id: components["parameters"]["ObjectiveId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposed plan containing two to five work items. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    revisePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objective_id: components["parameters"]["ObjectiveId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRevision"];
            };
        };
        responses: {
            /** @description Revised proposed plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    approvePlan: {
        parameters: {
            query?: never;
            header: {
                /** @description Reusing a key returns the original run and never starts another. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                objective_id: components["parameters"]["ObjectiveId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved plan and the one run started for this key. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listWorkItems: {
        parameters: {
            query?: {
                objective_id?: string;
                status?: components["schemas"]["WorkItemStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Work items ordered by objective and position. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItem"][];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRunEvents: {
        parameters: {
            query?: {
                /** @description Return events with a greater sequence number. */
                after_sequence?: number;
            };
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted events in ascending sequence order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvent"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Last received run-event sequence. */
                "Last-Event-ID"?: number;
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted run events as Server-Sent Events. */
            200: {
                headers: {
                    "Cache-Control"?: "no-cache";
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRunArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest artifact versions for the run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
